export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_ERROR = 'GET_WEATHER_DATA_ERROR';
export const ON_PREVIOUS_BUTTON_CLICK = 'ON_PREVIOUS_BUTTON_CLICK';
export const ON_NEXT_BUTTON_CLICK = 'ON_NEXT_BUTTON_CLICK';
export const ON_YEAR_SELECT = 'ON_YEAR_SELECT';